name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          store-path: |
            $(nix-build --no-out-link -E '(import <nixpkgs> {}).aseprite')
          key: ${{ runner.os }}-nix-aseprite

      - name: Build with Nix
        run: |
          nix-shell --run "just ci"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wins-*.tar
